listing = ["overlayedCells0pD0.mat","overlayedCells25pD0.mat","overlayedCells50pD0.mat","overlayedCells75pD0.mat",...
    "overlayedCells0pD2.mat","overlayedCells25pD2.mat","overlayedCells50pD2.mat","overlayedCells75pD2.mat",...
    "overlayedCells0pD4.mat","overlayedCells25pD4.mat","overlayedCells50pD4.mat","overlayedCells75pD4.mat",...
    "overlayedCellsD20p.mat","overlayedCellsD225p.mat","overlayedCellsD250p.mat","overlayedCellsD275p.mat",...
    "overlayedCellsD40p.mat","overlayedCellsD425p.mat","overlayedCellsD450p.mat","overlayedCellsD475p.mat"];
for i = 1:size(listing,2)
    load(listing(i));
    cellPosStruct = dataStruct;
    cellDensityBinPlot
end